### PR TITLE
Scatter chart

### PR DESCRIPTION
**Pull request by buren**
* Adds `ScatterChart`
* ~~Adds `hAxisTitle` & `vAxisTitle` options~~

### CODE REVIEW

**Comment by ankane** [comment]
Thanks Jacob, would love to add scatter charts!  Can you divide this into separate commits for the scatter chart and title options?  Also, we can make all data from scatter charts numeric, so I don't think we'll need the `raw` option.

**Comment by buren** [comment]
No, thank you Andrew for an awesome library! :+1: 

Scatter charts can actually have dates as x-values, so thats why I figured something like `raw` was needed. Anyways perhaps its best, like you say, to always convert it to a number, since thats probably what people are gonna use it for :)

I'll remove the `raw` option and always convert to a number & split the scatter chart & title options to separate commits :) 

What do you think about the option names? `hAxisTitle` & `vAxisTitle`? Any other suggestions?

**Comment by buren** [comment]
@ankane I've removed `hAxisTitle` & `vAxisTitle` options and I'll create a new PR with those added.

Let me know if you have any other suggestions/comments and then I'll squash these changes together.

**Comment by buren** [comment]
_note_: Also I extracted some code in `processSeries` into to two anonymous functions: https://github.com/ankane/chartkick.js/pull/47/files#diff-88d673ba779bb5d0e94d04dc6b53bbd6R755 I can revert those if you liked it better the way it was before.

**Comment by ankane** [comment]
A few notes:
- Ideally, the `time` parameter of `processSeries` can be changed to `keyType` so we don't have to modify options.
- Would be good to have an example for a single series in both the readme (to keep things consistent) and examples.html
- Would be good to pull the anonymous functions out of `processSeries` so they aren't recreated for each chart

**Comment by buren** [comment]
Thanks for the feedback! I'll get on it :)

**Comment by buren** [comment]
I've updated according to your feedback and I think its starting to look pretty OK. Let me know if you have any final thoughts/suggestions before I squash this commits together?

**Comment by ankane** [comment]
Looking very nice. Squash away!

**Comment by buren** [comment]
Squashed :)

**Comment by ankane** [comment]
Awesome, thanks for all the hard work!

**Comment by buren** [comment]
My pleasure :) Thanks for an awesome library

**Pull request merged**
