### PR TITLE
Add updateChart and updateAllCharts methods

### PR DESCRIPTION
**Pull request by buren**
Two methods have been added to `Chartkick`:

``` JavaScript
// Update one chart
Chartkick.updateChart('chart-id');               // Update chart from the current dataSource
Chartkick.updateChart('chart-id', newRemoteUrl); // Update chart from URL

// Update all charts
Chartkick.updateAllCharts(); // Updates from current `dataSource`
Chartkick.updateAllCharts(function(chart) {
  return chart.dataSource + '?some_param=abc';
}); // Updates all charts and appends ?some_param=abc to each chart's dataSource
```

This also allows for simple pull-based updates of any chart:

``` JavaScript
// Updates user-registration-chart every 10 seconds
setInterval(function() {
  Chartkick.updateChart('user-registration-chart');
}, 10000);
```

Thank you for a great library!

### CODE REVIEW

**Comment by phlegx** [comment]
+1 nice! This is what I need!

**Comment by buren** [comment]
Optionally there is also this commit https://github.com/buren/chartkick.js/commit/d307b3b52a8c6d308160ca88951a30e0b050a882 that also implements a `refresh` options where you can define how often you want the chart updated. 

Ping @phlegx

**Comment by bsbodden** [comment]
+1 much needed PR

**Comment by ankane** [comment]
Hey @buren, thanks for putting this together 👍  This is now possible on master with:

```javascript
var chart = Chartkick.charts["chart-1"];
chart.updateData(newData, newOptions);
```

To update all, you can use:

```javascript
Chartkick.eachChart( function(chart) {
  chart.updateData(chart.getDataSource() + "?some_param=abc", {colors: ["red", "green"]});
});
```

Let me know if I missed anything.

**Comment by buren** [comment]
@ankane :+1:

**Comment by buren** [comment]
Noticed that you've started working a bit on this again. Happy to help with my other open PRs or close them if they're out of scope.

**Pull request closed without merging**
