### PR TITLE
Add dateFormat

### PR DESCRIPTION
**Pull request by thekeenant**

### CODE REVIEW

**Comment by ankane** [comment]
Thanks @KyloCode, can you give examples of different formats with each library?

**Comment by buren** [comment]
Highcharts dateformatting works, however Google does not, see https://github.com/google/google-visualization-issues/issues/797#issuecomment-100512053

**Comment by buren** [comment]
@ankane, @KyloCode in https://github.com/buren/chartkick.js/issues/4 I've fixed the google date format issue and updated the readme.

**Comment by ankane** [comment]
Cleaning up old PRs. Thanks again for your work on this @thekeenant.

**Pull request closed without merging**
