### PR TITLE
Adds xtitle & ytitle options

### PR DESCRIPTION
**Pull request by buren**
Support for `hAxisTitle` & `vAxisTitle` options for all charts.

As per https://github.com/ankane/chartkick.js/pull/47#issuecomment-134474115

Do you like the option names? I had some trouble choosing what to use.. `xAxis`, `xAxisLabel`, `xAxisTitle` etc etc...

### CODE REVIEW

**Comment by ankane** [comment]
What do you think of `xtitle` and `ytitle`?

**Comment by buren** [comment]
Updated and squashed :)

**Comment by ankane** [comment]
Cool, I won't be around later this week, but I'll get this merged next week.

**Comment by buren** [comment]
Sweet :+1:

**Comment by ankane** [comment]
Merged, thanks!

**Comment by ankane** [comment]
Also, pushed a new version of chartkick.js and the chartkick gem with this and the scatter charts :+1:

**Comment by buren** [comment]
Sweet 👑

**Pull request merged**
